<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Kegiatan_model extends CI_Model
{

    public $table = 'kegiatan';
    public $id = 'id_kegiatan';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

     // get id_kegiatan by jenis dan idunit
     function get_id_kegiatan($i,$id)
     {
         $this->db->select('id_kegiatan');
         $this->db->join('m_dat', 'kegiatan.kode_m_dat=m_dat.kode','left');
         $this->db->where('id_unit', $id);
         $this->db->where('jenis', $i);
         return $this->db->get($this->table)->row();
     }

    // get sum by jenis dan idunit
    function sum($i,$id)
    {
        $this->db->select('sum(jumlah) as sum');
        $this->db->join('m_dat', 'kegiatan.kode_m_dat=m_dat.kode','left');
        $this->db->where('id_unit', $id);
        $this->db->where('jenis', $i);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_kegiatan', $q);
	$this->db->or_like('id_kegiatan', $q);
	$this->db->or_like('kode_m_dat', $q);
	$this->db->or_like('volume', $q);
	$this->db->or_like('satuan', $q);
	$this->db->or_like('jumlah', $q);
	$this->db->or_like('id_unit', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->like('id_kegiatan', $q);
	$this->db->or_like('id_kegiatan', $q);
	$this->db->or_like('kode_m_dat', $q);
	$this->db->or_like('volume', $q);
	$this->db->or_like('satuan', $q);
	$this->db->or_like('jumlah', $q);
    $this->db->or_like('id_unit', $q);
    $this->db->join('m_dat', 'kegiatan.kode_m_dat=m_dat.kode');
	$this->db->limit($limit, $start);
	$this->db->order_by('kode_m_dat', 'ASC');
        return $this->db->get($this->table)->result();
    }

    // get jumlah anak by id
    function count_child($i)
    {
        $result=$this->db->query ('SELECT count(*) as jumlah_anak FROM kegiatan JOIN m_dat
                     ON kegiatan.kode_m_dat = m_dat.kode WHERE m_dat.induk = 
                     (select kode_m_dat from kegiatan limit '.$i.',1)')->row();
        return $result;
    }

    // count kegiatan
    function count_kegiatan()
    {
        $result=$this->db->query ('SELECT count(*) as "count" from kegiatan')->row();
        return $result;
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }



    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    // delete bulkdata
    function deletebulk(){
        $data = $this->input->post('msg_', TRUE);
        $arr_id = explode(",", $data); 
        $this->db->where_in($this->id, $arr_id);
        return $this->db->delete($this->table);
    }
//check pk data is exists 

        function is_exist($id){
         $query = $this->db->get_where($this->table, array($this->id => $id));
         $count = $query->num_rows();
         if($count > 0){
            return true;
         }else{
            return false;
         }
        }


}

/* End of file Kegiatan_model.php */
/* Location: ./application/models/Kegiatan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-07-08 18:29:18 */
/* http://harviacode.com */