<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class M_dat_model extends CI_Model
{

    public $table = 'm_dat';
    public $id = 'kode';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get data m_dat induk
    function get_m_dat_induk($jenis)
    {
        $this->db->where('jenis', $jenis);
        $result = $this->db->get($this->table);

        $dd[''] = '--Pilih Kegiatan --';
        if ($result->num_rows() > 0) {
            foreach ($result->result() as $row) {
            // tentukan value (sebelah kiri) dan labelnya (sebelah kanan)
                $dd[$row->kode] = $row->kode.'-'.$row->ket;
            }
        }
        return $dd;
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('kode', $q);
	$this->db->or_like('kode', $q);
	$this->db->or_like('ket', $q);
	$this->db->or_like('induk', $q);
	$this->db->or_like('jenis', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('kode', $q);
	$this->db->or_like('kode', $q);
	$this->db->or_like('ket', $q);
	$this->db->or_like('induk', $q);
	$this->db->or_like('jenis', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    // delete bulkdata
    function deletebulk(){
        $data = $this->input->post('msg_', TRUE);
        $arr_id = explode(",", $data); 
        $this->db->where_in($this->id, $arr_id);
        return $this->db->delete($this->table);
    }
//check pk data is exists 

        function is_exist($id){
         $query = $this->db->get_where($this->table, array($this->id => $id));
         $count = $query->num_rows();
         if($count > 0){
            return true;
         }else{
            return false;
         }
        }


}

/* End of file M_dat_model.php */
/* Location: ./application/models/M_dat_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-07-05 02:23:18 */
/* http://harviacode.com */