<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tahun_model extends CI_Model
{

    public $table = 'tahun';
    public $id = 'id_tahun';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_tahun,tahun,aktif');
        $this->datatables->from('tahun');
        //add this line for join
        //$this->datatables->join('table2', 'tahun.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('tahun/set/$1'),'<i class="fa fa-check-square"></i>', 'class="btn btn-xs btn-primary"  data-toggle="tooltip" title="Set Aktif"')."  ".anchor(site_url('tahun/update/$1'),'<i class="fa fa-edit"></i>', 'class="btn btn-xs btn-warning" data-toggle="tooltip" title="Edit"')."  ".anchor(site_url('tahun/delete/$1'),'<i class="fa fa-trash"></i>', 'class="btn btn-xs btn-danger" onclick="return confirmdelete(\'tahun/delete/$1\')" data-toggle="tooltip" title="Delete"'), 'id_tahun');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get id by tahun aktif
    function get_by_aktif()
    {
        $this->db->where('aktif', '1');
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_tahun', $q);
	$this->db->or_like('tahun', $q);
	$this->db->or_like('aktif', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_tahun', $q);
	$this->db->or_like('tahun', $q);
	$this->db->or_like('aktif', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // update data sisa
    function update2($id, $data)
    {
        $this->db->where('id_tahun !=', $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    // delete bulkdata
    function deletebulk(){
        $data = $this->input->post('msg_', TRUE);
        $arr_id = explode(",", $data); 
        $this->db->where_in($this->id, $arr_id);
        return $this->db->delete($this->table);
    }


}

/* End of file Tahun_model.php */
/* Location: ./application/models/Tahun_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-07-12 18:11:28 */
/* http://harviacode.com */